#+AUTHOR: Evan DELEPINE
#+DATE: <2025-10-17 Fri>

* COFFEE-MACHINE : Le travail efficace pour les nuls

Chez nos amis développeurs, on entend souvent dire "Emacs est trop
compliqué, le jeu n'en vaut pas la chandelle"

Seulement, nous sommes persuadés que c'est faux, ou en partie.

En effet, Emacs n'est pas forcément compliqué, et peut s'avérer très
robuste et efficace, surtout quand on sait comment s'y prendre

C'est ici que nous intervenons, grâce à cette configuration emacs et
i3 faite avec *amour*, nous projetons de rendre le travail efficace
simple à mettre en place, ce qui peut paraître compliqué.

* Installation du projet Coffee Machine

** 1. Cloner le dépôt
Il suffit simplement de cloner le dépôt du projet.

#+begin_src sh
git clone https://github.com/evan-chapignon/coffee-machine/
#+end_src

** 2. Installation des dépendances
Les dépendances varient selon votre distribution Linux.

*** Debian / Ubuntu

#+begin_src sh
sudo apt update
sudo apt install emacs i3 polybar
#+end_src

*** Arch Linux / Manjaro

#+begin_src sh
sudo pacman -Syu emacs i3 polybar
#+end_src

*** Fedora

#+begin_src sh
sudo dnf install emacs i3 polybar
#+end_src

** 3. Installation des la polices Iosevka Nerd Font
:PROPERTIES:
:ID: install-iosevka-font
:END:

*** Iosevka Nerd Font
Cette police est utilisée dans Polybar.

#+begin_src sh
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Iosevka.zip
unzip Iosevka.zip -d ~/.local/share/fonts/
fc-cache -fv
#+end_src

** 4. Vérification
Vous pouvez vérifier que la police est bien installée :

#+begin_src sh
fc-list | grep "Iosevka"
#+end_src

** A qui s'addresse notre travail ?

Ces configurations s'addressent principalement aux *étudiants en
informatique*, et permet le *développement* ainsi que la *prise de note*
dans le *confort*, et *sans souris*!
