#+AUTHOR: Evan DELEPINE
#+DATE: <2025-10-17 Fri>
#+property: header-args :results none

* Emacs pour les nuls

DISCLAIMER : Nous partons du principe que vous avez fait le [[elisp:(help-with-tutorial)][tutoriel
d'emacs]] (C-h t (Ce qui signifie CTRL+H, puis t)) 

** Les modes

Un mode est une fonction permettant de modifier le fonctionnement de
emacs de plusieurs manières, allant de l'affichage de l'interface
utilisateur aux raccourcis clavier.

Ici, on garde les menus supérieurs, le but étant de regarder quel
raccourci est associé à quelle action. On pourra retirer les modes à
l'avenir en remplaçant "1" par "-1"

#+begin_src elisp
  (menu-bar-mode 1)
  (tool-bar-mode 1)
#+end_src
 
Je trouve judicieux d'activer le CUA (Common User Access), c'est à
dire les raccourcis d'édition classiques (C-x, C-c, C-v, C-z), qui
sont communs à beaucoup de logiciels de traitement de texte (Word,
Visual Studio Code, Intellij et j'en passe).

#+begin_src elisp
  (cua-mode 1)
#+end_src

Dans un but d'esthétisme, la barre de défilement sera otée.

#+begin_src elisp
  (scroll-bar-mode -1)
#+end_src

Aussi, on veut voir le numéro des lignes (Toujours mieux pour déboguer
du code ;))

#+begin_src elisp
  (global-display-line-numbers-mode 1)
#+end_src

** Les paquets à installer

On initialise MELPA (une archive de paquets pour emacs)

#+begin_src elisp
  (require 'package)
  (add-to-list 'package-archives
  		   '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

*** MAGIT

Gestionnaire git pour emacs

Cheat sheet :
- C-x g : ouvrir magit
- s : add le fichier
- c c : écrire le message de commit
- C-c C-c : commit
- F p : pull
- P p : push

#+begin_src elisp
  (use-package magit
  :ensure t
  :bind (("C-x g" . magit-status)))
#+end_src

*** Vertico

VERTical Interactive COmpletion

Tout est dans le nom

#+begin_src elisp
  (use-package vertico
  :init
  (vertico-mode))
#+end_src


  
