#+AUTHOR: Evan DELEPINE
#+DATE: <2025-10-17 Fri>
#+property: header-args :results none

* Emacs pour les nuls

DISCLAIMER : Nous partons du principe que vous avez fait le [[elisp:(help-with-tutorial)][tutoriel
d'emacs]] (C-h t (Ce qui signifie CTRL+H, puis t)) 

** Les modes

Un mode est une fonction permettant de modifier le fonctionnement de
emacs de plusieurs manières, allant de l'affichage de l'interface
utilisateur aux raccourcis clavier.

Ici, on garde les menus supérieurs, le but étant de regarder quel
raccourci est associé à quelle action. On pourra retirer les modes à
l'avenir en remplaçant "1" par "-1"

#+begin_src elisp
  (menu-bar-mode 1)
  (tool-bar-mode 1)
#+end_src
 
Je trouve judicieux d'activer le CUA (Common User Access), c'est à
dire les raccourcis d'édition classiques (C-x, C-c, C-v, C-z), qui
sont communs à beaucoup de logiciels de traitement de texte (Word,
Visual Studio Code, Intellij et j'en passe).

#+begin_src elisp
  (cua-mode 1)
#+end_src

Dans la même veine, j'active un mode qui permet de remplacer la
sélection par le caractère inséré dans la sélection

#+begin_src elisp
(delete-selection-mode 1)
#+end_src

Dans un but d'esthétisme, la barre de défilement sera otée.

#+begin_src elisp
  (scroll-bar-mode -1)
#+end_src

Aussi, on veut voir le numéro des lignes (Toujours mieux pour déboguer
du code ;))

#+begin_src elisp
  (global-display-line-numbers-mode 1)
#+end_src

Voir ce qu'on séléctionne avec C-Space

#+begin_src elisp
(transient-mark-mode 1)
#+end_src

Mettre en surbrillance la ligne actuelle :

#+begin_src elisp
(global-hl-line-mode 1)
#+end_src


*** Les parentèses

Parce que c'est mieux quand l'éditeur le fait pour nous

#+begin_src elisp
  (show-paren-mode 1)
  (electric-pair-mode 1)
#+end_src

** Les paquets à installer

On initialise MELPA (une archive de paquets pour emacs)

#+begin_src elisp
  (require 'package)
  (add-to-list 'package-archives
  		   '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src


*** MAGIT

Gestionnaire git pour emacs

Cheat sheet :
- C-x g : ouvrir magit
- s : add le fichier
- c c : écrire le message de commit
- C-c C-c : commit
- F p : pull
- P p : push

#+begin_src elisp
  (use-package magit
  :ensure t
  :bind (("C-x g" . magit-status)))
#+end_src


*** Vertico

VERTical Interactive COmpletion

Tout est dans le nom

#+begin_src elisp
  (use-package vertico
  :init
  (vertico-mode))
#+end_src


*** Modeline

Code repompé chez https://github.com/evan-chapignon/emacs (Pensez à
mettre une petite star sur mes projets ;))

#+begin_src elisp
      (use-package mood-line)

      (mood-line-mode 1)

      (display-battery-mode 1)
      (display-time-mode 1)
      (setq display-time-format "%H:%M"
  		  display-time-default-load-average nil)

       (setq battery-mode-line-format " [BAT%p%%]")
#+end_src


*** Thème

Le thème est à retrouver dans [[./theme.org]]


*** Avy

Très puissant, permet d'entrer un caractère avec C-', puis, taper un
autre caractère correspondant pour s'y rendre, le meilleur moyen de
comprendre son effet est d'essayer

#+begin_src elisp
(use-package avy
  :bind ("C-'" . avy-goto-char))
#+end_src

Faites C-', puis essayez de vous rendre sur chacun des caractères
ci-dessous :

QSDF JKLM


*** Which key

Vous affiche les options possibles après un raccourci

#+begin_src elisp
(use-package which-key
  :init (which-key-mode)
  :config (setq which-key-idle-delay 0.3))
#+end_src

Essayez de faire C-x et d'attendre un peu.


*** Marginalia

Description des commandes M-x, indispensable

#+begin_src elisp
(use-package marginalia
  :after vertico
  :init (marginalia-mode))
#+end_src


*** Consult

Recherche et commandes améliorées

#+begin_src elisp
  (use-package consult)
  (global-set-key (kbd "C-s") 'consult-line)  
  (global-set-key (kbd "C-x b") 'consult-buffer)
  (global-set-key (kbd "M-y") 'consult-yank-pop)
  (global-set-key (kbd "C-c m") 'consult-imenu) 
#+end_src


*** LSP

Language Server Protocol, intégration pour les fichiers de code en
général

#+begin_src elisp
(use-package lsp-mode
  :ensure t
  :init
  (setq lsp-keymap-prefix "C-c l")
  :hook ((prog-mode . lsp-deferred))
  :commands (lsp lsp-deferred))
#+end_src


** QOL

Gérer les fichiers de backups :

#+begin_src elisp
(setq make-backup-files nil)
(setq auto-save-default nil)
#+end_src

Simplifier la confirmation (yes/no)

#+begin_src elisp
(fset 'yes-or-no-p 'y-or-n-p)
#+end_src

** Java

Cette section a été séparée vers le fichier [[./java.org]], décommentez la
ligne correspondate dans le [[init.el]] pour activer les fonctionnalités java.
