#+AUTHOR: Jonas FACON
#+DATE: <2025-10-18 Sat>

* Polybar pour les nuls
Tout bureau qui se respecte doit avoir une belle et utile barre d'état.

* Introduction
Ici vous retrouverez toute la configuration pour une barre simple et utile, mais aussi, pour les plus créatifs d'entre vous, des modules que vous pourrez décider d'utiliser ou non, plus ou moins utiles.

** Les couleurs
Dans la configuration ci-dessous, vous verrez souvent `=${colors.<couleur>}=`, ce qui permet d'adapter Polybar au thème que vous avez choisi.  
Pour plus d'informations sur les couleurs utilisées par thème, consultez les fichiers se trouvant dans [[file:themes/][themes/]].

Pour importer le thème :  
#+begin_src ini
include-file = $HOME/.config/polybar/themes/<flavor>.ini
#+end_src

** Les polices (fonts)
Nous utilisons la police *Iosevka Nerd* pour les icônes et *Cantarell* pour le reste. Pensez donc à les installer si ce n'est pas déjà fait.  
Un guide d'installation est disponible : [[file:../../README.org::#install-iosevka-font][Installation des polices]]

* La barre en tant que telle
#+begin_src ini
[bar/Newbie]
width = 100%
height = 30
background = ${colors.base}
foreground = ${colors.text}
line-size = 2
border-size = 0
padding-right = 4
padding-left = 4
padding-top = 3
module-margin = 3
separator = .
separator-foreground = ${colors.subtext0}
font-0 = Noto Sans:size=10;1
font-1 = Cantarell:style=Bold:size=12;2
font-2 = Iosevka Nerd Font:size=10;2
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
#+end_src

Pour disposer vos modules sur la Polybar et choisir ce que vous voulez afficher, vous avez 3 options possibles :  
- À gauche  
- Au centre  
- À droite  

Voici notre sélection recommandée :  
#+begin_src ini
modules-left = xworkspaces xwindow
modules-center = date
modules-right = pulseaudio xkeyboard network battery
#+end_src

* Les Modules

** Xworkspaces
Ce module, ainsi que le suivant, est selon moi le plus utile et pratique.  
Il permet de savoir combien de workspaces sont utilisés ainsi que celui sur lequel vous vous trouvez.

#+begin_src ini
[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.surface2}
label-active-underline = ${colors.lavender}
label-active-padding = 2
label-occupied = %name%
label-occupied-padding = 2
label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 2
label-empty = %name%
label-empty-foreground = ${colors.subtext0}
label-empty-padding = 2
#+end_src

** Xwindow
Ce module vous indique dans quelle fenêtre vous vous trouvez, très pratique quand vous commencez à avoir un bon nombre de fenêtres ouvertes sur votre bureau.

#+begin_src ini
[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-foreground = ${colors.flamingo}
#+end_src

** Xkeyboard
#+begin_src ini
[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-foreground = ${colors.lavender}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.sky}
#+end_src

** Date
La classique date et heure.

#+begin_src ini
[module/date]
type = internal/date
date = %A, %d %B %Y %H:%M
label = %{T2} %date%%{T-}
#+end_src

** Pulseaudio
Petit module pour savoir si le son des haut-parleurs est activé.

#+begin_src ini
[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
label-volume = %{T3}  %{T-} %percentage%%
label-muted = %{T3}  %{T-}
label-muted-foreground = ${colors.green}
label-volume-foreground = ${colors.green}
#+end_src

** Network
Module pour le réseau, essentiel pour les débutants qui ne savent pas forcément s'ils sont connectés à Internet.

#+begin_src ini
[module/network]
type = internal/network
interface = ${env:IFACE}
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = %{T3} 󰖩 %{T-} %essid%
label-disconnected = %{T3} 󰖪 %{T-} Déconnecté
label-connected-foreground = ${colors.yellow}
label-disconnected-foreground = ${colors.peach}
#+end_src

** Battery
Module avec animation de charge.

#+begin_src ini
[module/battery]
type = internal/battery
battery = ${env:BAT}
adapter = ${env:ADP}
format-charging = <label-charging> <animation-charging> 
format-discharging = <label-discharging> <ramp-capacity>
format-full = <label-full>
label-charging = "⚡ %percentage%% "
label-discharging = "%percentage%% "
label-full = "100% 󰁹"
ramp-capacity-0 = 󰂎
ramp-capacity-1 = 󰁺
ramp-capacity-2 = 󰁻
ramp-capacity-3 = 󰁼
ramp-capacity-4 = 󰁽
ramp-capacity-5 = 󰁾
ramp-capacity-6 = 󰁿
ramp-capacity-7 = 󰂀
ramp-capacity-8 = 󰂁
ramp-capacity-9 = 󰂂
ramp-capacity-10 = 󰂂
ramp-capacity-11 = 󰁹
animation-charging-0 = 󰂎
animation-charging-1 = 󰁺
animation-charging-2 = 󰁻
animation-charging-3 = 󰁼
animation-charging-4 = 󰁽
animation-charging-5 = 󰁾
animation-charging-6 = 󰁿
animation-charging-7 = 󰂀
animation-charging-8 = 󰂁
animation-charging-9 = 󰂂
animation-charging-10 = 󰂂
animation-charging-11 = 󰁹
animation-charging-framerate = 500
#+end_src

* Modules pour les créatifs

** Weather
Module météo.

#+begin_src ini
[module/weather]
type = custom/script
exec = curl -s "https://wttr.in/?m&lang=fr&format=%C+%t+%w" 
interval = 600
#+end_src

** Music
Affiche les informations de la musique en cours sur Spotify.

#+begin_src ini
[module/music]
type = custom/script
exec = "playerctl metadata --format '🎵 {{artist}} - {{title}}'"
label-foreground = ${colors.mauve}
#+end_src

** Temp
Pour surveiller la température du PC et des composants.

#+begin_src ini
[module/temp]
type = custom/script
exec = "sensors | grep 'Package id 0:' | awk '{print $4}'"
label = 🌡 %output%
label-foreground = ${colors.blue}
#+end_src

** Git
Module qui montre l’état du repo courant (branche, changements).

#+begin_src ini
[module/git]
type = custom/script
exec = "git -C /path/to/repo status -s | wc -l"
interval = 10
label = 🌿 %output% changes
label-foreground = ${colors.green}
#+end_src

* Ressources utiles
- Documentation officielle Polybar : https://polybar.github.io  
- Thèmes Catppuccin : https://github.com/catppuccin/polybar  
- Polices Iosevka : https://github.com/be5invis/Iosevka  
- Guide d'installation des polices Nerd et des dépendances : [[file:../../README.org][ici]]
